apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    team: developers
    app: front-end
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80 
    